myshop/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^create/$', views.order_create, name='order_create'),
]

myshop/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.product_list, name='product_list'),
	url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

oliviaFlowers/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.home.urls', namespace='home')),
    url(r'^about', include('apps.about.urls', namespace='about')),
    url(r'^service', include('apps.services.urls', namespace='services')),
    url(r'^cart/', include('myshop.cart.urls', namespace='cart')),  
    url(r'^orders/', include('myshop.orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('myshop.payment.urls', namespace='payment')),
    url(r'^shop/', include('myshop.shop.urls', namespace='shop')),
]

myshop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
	quantity = forms.TypedChoiceField(
								choices=PRODUCT_QUANTITY_CHOICES,
								coerce=int)
	update = forms.BooleanField(required=False,
								initial=False,
								widget=forms.HiddenInput)

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from ..shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	form = CartAddProductForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
		cart.add(product=product,
				quantity=cd['quantity'],
				update_quantity=cd['update'])
	return redirect('cart:cart_detail')

def cart_remove(request, product_id):
	cart = Cart(request)
	product = get_object_or_404(Product, id=product_id)
	cart.remove(product)
	return redirect('cart:cart_detail')

def cart_detail(request):
	cart = Cart(request)
	for item in cart:
		item['update_quantity_form'] = CartAddProductForm(
							initial={'quantity': item['quantity'],
							'update': True})
	return render(request, 'cart/details.html', {'cart': cart})

myshop/cart/templates/cart/details.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
	Your shopping cart
{% endblock %}

{% block content %}
	<h1>Your shopping cart</h1>
	<table class="cart">
		<thead>
			<tr>
				<th>Image</th>
				<th>Product</th>
				<th>Remove</th>
				<th>Unit price</th>
				<th>Price</th>
			</tr>
		</thead>
		<tbody>
			{% for item in cart %}
				{% with product=item.product %}
				<tr>
					<td>
						<a href="{{ product.get_absolute_url }}">
							<img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
						</a>
					</td>
					<td>{{ product.name }}</td>
					<td>
						<form action="{% url "cart:cart_add" product.id %}" method="post">
							{{ item.update_quantity_form.quantity }}
							{{ item.update_quantity_form.update }}
							<input type="submit" value="Update">
							{% csrf_token %}
						</form>
					</td>
					<td><a href="{% url "cart:cart_remove" product.id %}">Remove</a></td>
					<td class="num">${{ item.price }}</td>
					<td class="num">${{ item.total_price }}</td>
				</tr>
				{% endwith %}
			{% endfor %}
			<tr class="total">
				<td>Total</td>
				<td colspan="4"></td>
				<td class="num">${{ cart.get_total_price }}</td>
			</tr>
		</tbody>
	</table>
	<p class="text-rigth">
		<a href="{% url "shop:product_list" %}" class="button light">Continue shopping</a>
		<a href="{% url "orders:order_create" %}" class="button">Checkout</a>
	</p>
{% endblock %}