apps/about/urls.py
from django.conf.urls import url
from . import views 

app_name='about'
urlpatterns = [
	url(r'^$', views.index, name='index')
]

apps/home/urls.py
from django.conf.urls import url 
from . import views

urlpatterns = [
	url(r'^$', views.index, name='home')
]

apps/navbar/urls.py
from django.conf.urls import url 
from . import views

urlpatterns = [
	url(r'^$', views.navbar, name='navbar'),
]

myshop/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.cart_detail, name='cart_detail'),
	url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

myshop/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.product_list, name='product_list'),
	url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

oliviaFlowers/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.home.urls', namespace='home')),
    url(r'^about', include('apps.about.urls', namespace='about')),
    url(r'^service', include('apps.services.urls', namespace='services')),
    url(r'^cart/', include('myshop.cart.urls', namespace='cart')),  
    url(r'^orders/', include('myshop.orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('myshop.payment.urls', namespace='payment')),
    url(r'^shop/', include('myshop.shop.urls', namespace='shop')),
]

apps/navbar/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/navbar/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect

def navbar(request):
	return render(request, 'navbar/nav.html')

apps/navbar/templates/navbar/nav.html
{% extends "myshop/shop/base.html" %}
{% load static %}

{% block navbar %}
	<nav>
		<ul>
			<li><a href="{% url 'home:home' %}">Home</a></li>
			<li>Shop<ul>
				<li><a href="{% url 'shop:product_list' %}">Browse</a></li>
				<li><a href="{% url 'order:order_create' %}">Place Order</a></li>
				<li><a href="{% url 'cart:cart_detail' %}"></a></li>
			</ul></li>
			<li><a href="{% url 'services:main' %}">Services</a></li>
			<li><a href="{% url 'about:index' ">Our Tale</a></li>
			<li><a href="#">Contact Us</a></li>
			<li><a href="#">Press</a></li>
		</ul>
	</nav>
{% endblock %}