apps/about/urls.py
from django.conf.urls import url
from . import views 

app_name='about'
urlpatterns = [
	url(r'^$', views.index, name='index')
]

apps/home/urls.py
from django.conf.urls import url 
from . import views

urlpatterns = [
	url(r'^$', views.index, name='home')
]

apps/services/urls.py
from django.conf.urls import url
from . import views
from django.contrib import messages
#from ..orders.models import Product

app_name='services'
urlpatterns = [
	url(r'^$', views.index, name='main'),
	url(r'^events$', views.events, name='events'),
	url(r'^designs$', views.designs, name='designs'),
	url(r'^seasonal$', views.seasonal, name='seasonal')
]

myshop/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.product_list, name='product_list'),
	url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
	url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

oliviaFlowers/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.home.urls', namespace='home')),
    url(r'^about', include('apps.about.urls', namespace='about')),
    url(r'^service', include('apps.services.urls', namespace='services')),
    url(r'^cart/', include('myshop.cart.urls', namespace='cart')),  
    url(r'^orders/', include('myshop.orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('myshop.payment.urls', namespace='payment')),
    url(r'^shop/', include('myshop.shop.urls', namespace='shop')),
]

apps/home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect

# Create your views here.
def index(request):
	print '**INDEX**' * 250
	return render(request, 'home/index.html')

apps/home/templates/home/index.html
<html>
<head>
	<meta charset="UTF-8">
	<title>Flowers For The People</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static "css/index.css" %}">
	<link href="https://fonts.googleapis.com/css?family=Bonbon|Butterfly+Kids|Delius+Swash+Caps|Flavors|Griffy|Irish+Grover|Mystery+Quest|Ruge+Boogie|Sail|Spirax|Lobster" rel="stylesheet">
</head>
<body>
	<article>
		<header>
			<h1>Flowers For The People</h1>
			<nav>
				<ul>
					<li><a href="Home">Home</a></li>
					
					<li><a href="{% url "shop:product_list" %}">Shop</a>
						<ul>
							<li><a href="#">Place Order</a></li>
							<li><a href="#">Browse Catalog</a></li>
							<li><a href="#">Your Cart</a></li>
						</ul>
					</li>
					<li><a href="{% url 'services:main' %}">Services</a>
						<ul>
							<li><a href="delivers">Daily Deliveries</a></li>
							<li><a href="designs">Botanical Designs</a></li>
							<li><a href="Estate">Estate Services</a></li>
							<li><a href="Corporate">Corporate Services</a></li>
							<li><a href="Weddings">Weddings &amp; Events</a></li>
							<li><a href="Holiday_Decor">Holiday Decor</a></li>
						</ul>
					</li>
					<li><a href="AboutUs">About Us</a>
						<ul>
							<li><a href="{% url 'about:index' %}">About Us</a></li>
							<li><a href="ContactUs">Contact Us</a></li>
						</ul>
					</li>
					<li><a href="Press">Press</a></li>
				</ul>
			</nav>
		</header>
		<section id="contactUs">
			<p>Contact Us ###-###-####</p>
		</section>
	</article>
	<section class="main">
		<div id="social">
			<p>Social Media Block</p>
				<div id="widget">
					<p>place holder for widget</p>
					<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCIvYLj70g4GkBjLat9IpiuO-N7Hei1Ri2x_AzUuEdVk_PxtrFvA" alt="">
				</div>
			
				<img id="fbook"src="{% static "img/facebook.png"%}" alt="">
				<img id="twitter"src="{% static "img/twitter.png" %}" alt="">
				<img id="instagram"src="{% static "img/Instagram.jpg" %}" alt="">
			
		</div>
		<div id="storeHype">
			<h1>SHOP ONLINE NOW!!!!</h1>
			<h1>Check out our brand new online Store <a href="{% url "shop:product_list" %}">Here</a>!!!!!</h1>
		</div>
		<div id="mainSect">
			<p>Seasonal Product? Featured Product?</p>
			<img id="imgOne" src="http://www.fillmurray.com/140/100" alt="">
			<img id="imgTwo" src="http://www.fillmurray.com/200/300" alt="">
			<p id="lookAtit">Would You Just Look At That</p>
			<img id="wouldYou" src="https://pbs.twimg.com/media/CGmXIhBUAAAq-yQ.jpg" alt="">
		</div>
		<div id="newProd">
			<p>Newest Designs</p>
			<img id="cageOne" src="https://www.placecage.com/c/140/200" alt="">
			<img id="seagal" src="http://www.stevensegallery.com/140/200" alt="">
		</div>
	</section>
	<article class="lowerText">
		<img src="http://www.fillmurray.com/460/300" alt="">
	</article>
</body>
</html>